name: Download Metadata

on:
  workflow_dispatch: {}  
  # schedule:
  # - cron: '36 16 * * *' # IST 10PM+

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: python3 judgment-metadata.py
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest metadata: ${timestamp}" || exit 0
        git push

    - name: install dependencies
      run: pip install -r requirements.txt

    - name: generate clean csv
      run: python3 clean-metadata.py

    - name: commit and push clean csv
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest clean metadata: ${timestamp}" || exit 0
        git push

